import Head from 'next/head';
import prisma from '@/lib/prisma';


import { GetStaticProps } from 'next/types';

export const getStaticProps: GetStaticProps = async () => {
  let find;
  try {
    find = await prisma.person.findUnique({
      where: {
        email: process.env.TEST_USER_EMAIL,
      },
    });
  } catch(e) {
    console.error(e);
  } finally {
    const user = JSON.stringify(find);
    return {
      props: { user },
      revalidate: 10,
    };
  }
};

export default function Home({ }) {
  return (
    <>
      <Head>
        <title>Base App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
dashboard
      </main>
    </>
  );
}
