import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import prisma from '@/lib/prisma';
import { GetStaticProps } from 'next/types';

export const getStaticProps: GetStaticProps = async () => {

  const find = await prisma.person.findUnique({
    where: {
      id: process.env.TEST_USER_ID,
    },
  });

  const user = JSON.stringify(find);
  return {
    props: { user },
    revalidate: 10,
  };
};

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Base App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>hi there!</div>
      </main>
    </>
  );
}
