name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  cypress-run:
    env:
      DATABASE_URL: ${{ secrets.TEST_DATABASE_URL}}
      TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
    runs-on: ubuntu-latest
    environment: Production
    concurrency: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.5.1 # use the explicit version number
        with:
          build: npm run build
          start: npm start
  Deploy-Production:
    needs: cypress-run
    env:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      DATABASE_URL: ${{ secrets.DATABASE_URL}}
      TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
    runs-on: ubuntu-latest
    environment: Production
    concurrency: Production
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
