name: Playwright Tests

on:
  push:
    branches-ignore:
      - main

jobs:
  playwright-test:
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL}}
      TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm i
      - name: Run site
        run: npm run dev
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test