name: Playwright Tests

on:
  push:
    branches-ignore:
      - main

jobs:
  playwright-test:
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL}}
      TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
      TEST_USER_ID: ${{ secrets.TEST_USER_ID }}
      TEST_USER_PW: ${{ secrets.TEST_USER_PW }}
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm i
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test